### ISSUE TITLE
Password promt on Windows 7 fails

### ISSUE THREAD

**Issue by bitzl** [jedrichards/grunt-rsync#27]
I try to rsync some data from a Windows 7 notebook to Linux server using cwRsync and latest grunt-rsync. It fails when rsync should ask for my passphrase.

My Gruntfile:

```
module.exports = function(grunt) {

    grunt.initConfig({

        rsync: {
            options: {
                args: ['--verbose', '--chmod=777'],
                exclude: ['*.git', 'node_modules'],
                recursive: true
            },
            production: {
                options: {
                    src: './bitzl.com',
                    dest: '/home/marcus/bitzl.com',
                    host: 'marcus@bitzl.com',
                    syncDest: true
                }
            }
        }
    });

    grunt.loadNpmTasks('grunt-rsync');
}
```

The error:

```
Running "rsync:production" (rsync) task
rsyncing ./example.com >>> /home/marcus/bitzl.com
Shell command was: rsync ./bitzl.com marcus@bitzl.com:/home/marcus/bitzl.com --rsh ssh --recursive --delete --delete-exc
luded --exclude=*.git --exclude=node_modules --verbose --chmod=777
ERROR
Error: rsync exited with code 12
Warning: Task "rsync:production" failed. Use --force to continue.
Error: Task "rsync:production" failed.
    at Task.<anonymous> (D:\git\bitzl.com\node_modules\grunt\lib\util\task.js:200:15)
    at null._onTimeout (D:\git\bitzl.com\node_modules\grunt\lib\util\task.js:236:33)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

Aborted due to warnings.
```

Running the same on Linux works as expected. Running the Rsync command from above on Windows directly works as expexted, too.

If I can provide any help to solve this issue, feel free to ask.

**Comment by brosig** [comment]
I don't know your case, but if you don't have rsync on the destiny it doesn't work.
I've been struggling for a long time before figure it out
😂
